# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
    v.name = "ubuntu-lb-T2"
  end
  config.vm.network "private_network", ip: "11.0.0.3", virtualbox__intnet: "mynet"
  config.vm.provision "shell" do |s|
    s.inline="apt-get update"
    s.inline="apt-get upgrade -y"
    s.inline="apt-get install apache2 -y"
    s.inline="systemctl enable apache2"
    s.inline="systemctl start apache2"
  end
end
