# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
    v.name = "ubuntu-lb"
  end
  config.vm.network "private_network", ip: "11.0.0.1", virtualbox__intnet: "mynet"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provision "shell" do |s|
    s.inline="apt-get update"
    s.inline="apt-get upgrade -y"
    s.inline="apt-get install nginx -y"
  end
end
